package com.example.todo.model; //declares the package for the model/entity layer

import jakarta.persistence.*; //imports annotations needed for JPA (Java Persistence API) entity mapping

//marks this class as a JPA entity so it will be mapped to a table in the database
@Entity
public class Todo {

    //marks 'id' as the primary key of the table
    @Id
    //specifies that the ID should be auto-generated by the database (e.g., AUTO_INCREMENT in SQL)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //field for the task description
    private String task;

    //field to indicate whether the task is completed or not
    private boolean completed;

    //getter for ID
    public Long getId() {
        return id;
    }

    //getter and setter for task
    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    //getter and Setter for completed status
    public boolean isCompleted() {
        return completed;
    }

    public void setCompleted(boolean completed) {
        this.completed = completed;
    }
}
